### ISSUE TITLE
Error: Request aborted

### ISSUE THREAD

**Issue by krisfarr** [andrewrk/node-multiparty#131]
Closing tab while uploading to S3 causes server to crash. Is there a way to keep the upload in case the connection is terminated by the client?
```
uploads/569ce2c83e3f560afd71ef98/569ce30d3e3f560afd71ef99/dfYDr8cQ4Pp_U1vF2cMYW-HNx169.jpg
events.js:142
      throw er; // Unhandled 'error' event
      ^

Error: Request aborted
    at IncomingMessage.onReqAborted (/Users/kris/Projects/treehouse-mean/node_modules/multiparty/index.js:183:17)
    at emitNone (events.js:68:13)
    at IncomingMessage.emit (events.js:167:7)
    at abortIncoming (_http_server.js:281:11)
    at Socket.socketOnEnd (_http_server.js:426:7)
    at emitNone (events.js:73:20)
    at Socket.emit (events.js:167:7)
    at endReadableNT (_stream_readable.js:906:12)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickDomainCallback (node.js:410:17)
```

**Comment by dougwilson** [comment]
Hi! This is expected, because the client disconnecting aborts the request. This module raises an error so you can handle it as you see fit. The error you are seeing is because you did not add the proper `error` handles, and in Node.js, if you don't add them, your program will crash by default.

You can find the documentation for error handles at https://github.com/andrewrk/node-multiparty#error-err

If you are not sure still, please feel free to post your code and I can take a look at where your error handlers are missing according to the documentation :)!

**Comment by krisfarr** [comment]
Thanks for pointing that out :) 

Just in case some one else needs it's the form.on('error', ...) section.
